apiVersion: v1
kind: List
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: dwh-microservice-blank-slate
  spec: 
    concurrencyPolicy: Forbid 
    startingDeadlineSeconds: 600
    schedule: "0 4 * * *"
    jobTemplate:
      spec: 
        activeDeadlineSeconds: 3600 
        backoffLimit: 3
        template:
          spec:
            containers:
            - name: dwh-microservice-blank-slate
              image: eu.gcr.io/spil-infra-registry/dwh-microservice-blank-slate:0000000000
              args:
              - blank-slate
              envFrom:
              - configMapRef: 
              volumeMounts:
              - name: dwh-importer
                mountPath: /opt/secrets/service-account
              - name: dwh-adcolony-importer
                mountPath: /opt/config
            restartPolicy: Never
            volumes:
            - name: dwh-importer
              secret:
                secretName: dwh-importer 
